### ISSUE TITLE
Extend the survey service to work with Sunbird Knowlg Building Block

### ISSUE THREAD

**Issue by aks30** [shikshalokam/ml-survey-service#140]
---
name: C4GT DMP 2024 Issue
about: This issue explains the enhancements to be done for the service to make it work with Sunbird Knowlg service.
title: **Extend the survey service to work with Sunbird Knowlg Building Block #140**
labels: C4GT Community, DMP 2024, enhancement
mentor: @ankitpws 

---

## Description
Survey service enables collecting data, be it as a survey (a set of questions - e.g. a general form), an observation without a rubric (a set of questions for an entity - e.g. a feedback form with respect to a session / meeting / course), an observation with rubric (a set of questions for an entity but with automatic score calculation - e.g. a quiz for a course, an assessment of school). Currently, the APIs to consume the questions, fetch the data from MongoDB (an in-built datastore) and return the same. The scope of this ticket is to extend the service, to also read questions from the assessment service of Sunbird Knowlg Building block.

## Goals
- [x] Setup ML Survey service
- [x] Understand the code structure and flow
- [x] Understand the question response structure of current APIs
- [x] Understand the APIs of Sunbird Knowlg
- [ ] Build a new API
- [x] Write migrations

## Expected Outcome
Seamless Integration with Sunbird Knowledge Building Block.
Migration of Questionnaires from Survey Service to Sunbird Knowledge Building Block.
Migration of Solutions from Survey Service to Sunbird Knowledge Building Block.
Review and publishing of Questions and Solutions by designated Reviewers.

## Acceptance Criteria
- [ ] Develop Migration script for transferring Questionnaires from Survey Service to Sunbird Knowledge Building Block.
- [ ] Ensure Migration script includes a review process, marking all Questions as published upon reviewer approval.
- [ ] Once Questions are published, execute Migration script for Solutions, updating their status accordingly.
- [ ] All migrated data must be trackable, generating a CSV report containing all relevant statuses.
- [ ] Survey service works with Sunbird Knowlg BB

## Implementation Details
- [ ] Examine ml-survey service codebase for understanding migration requirements.
- [ ] Explore APIs within Sunbird Knowledge Building Block for migrating assets.
- [ ] Utilize learner service users APIs to search for users and organizations, checking for content reviewer and content publisher roles.
- [ ] Perform migration of Questions from Survey Service to Sunbird Knowledge Building Block.
- [ ] Implement a workflow for reviewer approval and publishing of Questions, ensuring integration with Solutions for consumption.
- [ ] If necessary, develop additional APIs to support migration and integration processes.

### Product Name
Sunbird Ed

### Organization Name:
ShikshaLokam

### Domain
Education, Learning and Development

### Tech Skills Needed:
Node.js

### Mentor(s)
@ankitpws

### Category
API, Backend

**Comment by jayesh9747** [comment]
@ankitpws here Sunbird Knowlg BB , means it is new repo another to this current repo  ? please explain in more details .

**Comment by jayesh9747** [comment]
![image](https://github.com/shikshalokam/ml-survey-service/assets/123955234/5d256773-a15b-427d-bde4-e77df44d9e5e)

**Comment by Sumsum1231** [comment]
Greetings@aks30 @ankitpws,
I want to connect with you guys so that I can understand about the issue more clearly.
I have worked with Shikhalokam and contributed to ELEVATE frontend-auth-lib and working on ELEVATE frontend-utils-lib.
Kindly guide me so that I can contribute to this project.

**Comment by Harsh06-afk** [comment]
Hey @ankitpws , I was setting up "ml-survey-service" 
I am facing some issue in  setting up the keycloak, can someone can help me with this?

**Comment by yashpatel139** [comment]
hey @aks30 @ankitpws I'm interested in this project can I work on this project ??

**Comment by akashsingh011** [comment]
Hello, @aks30 @ankitpws , I would like to contribute to this project. I have the required skillset for it. Kindly guide me so that I can contribute to this project.

**Comment by ankitpws** [comment]
Hi @jayesh9747 @akashsingh011 @yashpatel139 @Harsh06-afk @Sumsum1231,
Can you guys reach out to me on Discord - hi_Shanky

**Comment by AkanshuAich** [comment]
Hii @ankitpws ,

I am Akanshu Aich, a third year BTech student from International Institute of Information Technology, Bhubaneswar. I am writing to express my interest in contributing to this project as a part of DMP 2024. Having thoroughly reviewed the project, I am impressed by its objectives and it seeks the potential for great impact in industries.

With my background in Backend using Django , MERN with practicing hands on Machine learning and DevOps such as Docker, I believe I can make valuable contributions to Machine learning part . My experience includes several projects like Society-Expenditure Manager using Django, Real Estate using MERN and Info-Finding Tool using Machine Learning(LLM), which I believe align well with the goals of your project.

I am particularly interested in fulfilling the requirements of the project and have some ideas on how to approach it effectively. I am committed to adhering to best practices, contributing high-quality code, and actively collaborating with the project maintainers and community.

I am excited about the opportunity to contribute to "ShikshaLokam" and help further its mission. I look forward to discussing potential contributions and how I can best support the project.

Please guide me with procedure and with all your knowledge and experience.

**Comment by lodha1503** [comment]
Hi Ankit,

I hope this message finds you well. My name is Shreyansh Lodha, currently in my fourth year pursuing undergraduate studies at IIT Jodhpur. I am reaching out with great enthusiasm to express my keen interest in becoming a part of the Code4GovTech initiative, particularly in contributing to the "HIU Portal for Consent Management" project.

I am excited to highlight my involvement in my final year B.Tech project which was ABHA-NHA Integration to IIT Jodhpur Health System,where I worked with nodejs .I am eager to leverage my expertise to contribute meaningfully to the Code4GovTech initiative. 
I am confident that my meticulous insights and dedication will enable me to make valuable contributions to this program. I am eager to discuss how I can further support and collaborate on this important endeavor.

During my ongoing backend internship at AItoXR.AI, I have had the privilege of actively contributing to the development of robust services, implementing efficient algorithms using TypeScript, NodeJS, React Js, and Express Js.

Additionally, my experience extends to leadership roles, as evidenced by securing the 2nd position in the Prometeo Hackathon, where I led a team, showcasing my adeptness in problem-solving and team management.

My project portfolio reflects a diverse range of experiences, including the development of an E-Commerce web app and contributions to the IIT Jodhpur Telemedicine project using Google Cloud Platform, NodeJs, and TypeScript. These endeavors underscore my versatility and proficiency in various technologies.

Given my strong technical acumen in JavaScript, TypeScript, React Js, NodeJs, and others, coupled with a solid academic foundation in Data Structures, Algorithms, and related coursework.


I look forward to the opportunity to contribute to the Code4GovTech initiative.

Warm regards,
Shreyansh Lodha

**Comment by CodesSunny** [comment]
@ankitpws 
Dear Ankit, 
I am Vikas srivastava... I am a working finance pro with MBA... I have learned html, css, js, nodejs and continued... Pls let me know whether I can join this project... Pls reply. 
Thanks n Regards
Vikas

**Comment by memyselfandglitch** [comment]
Hi Ankit, 
I am Deveshi Singh, a third year undergraduate student at IIT(ISM) Dhanbad. I am a full stack developer and I have worked extensively with NodeJS. I am really looking forward to making a contribution to this project. Please guide me as to how to go about it.

Regards
Deveshi

**Comment by thesuryac** [comment]
hi , I am surya c  i have worked on nodejs projects on my personal projects. please guide me to contribute to this project

**Comment by Madhu-mac** [comment]
Hi @ankitpws, 
This is Madhu Lokesh, Currently working as a Full stack developer in a new-age startup "Drooid". I'm an Open-source enthusiast and also contributed to a few organizations previously. I have experience in MERN stack, Web dev & Mob Dev as well. I'm excited
about the project, it aligns with my expertise & I want to know more about it. 

I would love to collaborate and Contribute to "ShikshaLokam" and be a part of the community. Looking forward to discussing the project further.

**Comment by Nitish0777** [comment]
Hello, @aks30  @ankitpws ,I am very eager to contribute in this project And learn new thing from this open-source project.

**Comment by EuclidStellar** [comment]
HI **@ankitpws**,
I'm Gaurav Singh, currently a sophomore at AKGEC Ghaziabad. I'm passionate about coding and technology, especially when it comes to open-source projects. Having worked with MERN stack, web development, and mobile development, 
I'm eager to explore new opportunities for contributing and collaborating. I also bring experience from my time at the @Blockchain-Research-Lab where I've worked on exciting projects.

The project you mentioned, "ShikshaLokam," sounds intriguing, and I believe my skills align well with its goals. I'd love to learn more about it and discuss how I can be a part of the community. Looking forward to connecting further!

**Comment by testgithubtiwari** [comment]
Hii @ankitpws ,

I am Ritik Tiwari, a third year BTech student from Indian Institute of Technology, Jodhpur. I am writing to express my interest in contributing to this project as a part of DMP 2024. Having thoroughly reviewed the project, I am impressed by its objectives and it seeks the potential for great impact in industries.

With my background in Backend using Django , MERN with practicing hands on Machine learning and DevOps such as Docker, I believe I can make valuable contributions to Machine learning part . My experience includes several projects like  Digitalize thw Design Credit process using backend as Node.Js and frontend as Flutter,  Movie Recommender web app and many more , which I believe align well with the goals of your project.

I am particularly interested in fulfilling the requirements of the project and have some ideas on how to approach it effectively. I am committed to adhering to best practices, contributing high-quality code, and actively collaborating with the project maintainers and community.

I am excited about the opportunity to contribute to "ShikshaLokam" and help further its mission. I look forward to discussing potential contributions and how I can best support the project.

Please guide me with procedure and with all your knowledge and experience.

**Comment by ankitpws** [comment]
Hi @Nitish0777 @Madhu-mac @testgithubtiwari @EuclidStellar @thesuryac @memyselfandglitch @CodesSunny @lodha1503 @AkanshuAich @akashsingh011 @yashpatel139 @Harsh06-afk @Sumsum1231 @jayesh9747,

The contribution process will begin in a few weeks. However, if any of you are eager to start contributing, please feel free to let me know. I've scheduled a call for this Friday at 6 pm. Let's talk if you have any questions or doubts.
C4GT discussion 
Friday, April 19 · 6:00 – 6:30pm
Video call link: https://meet.google.com/vzo-oudm-yne

**Comment by AkanshuAich** [comment]
@ankitpws can we have any documentation related to it , so that we could properly understand the issue. Or all the doubts and briefing of the work will be done through the meet?

**Comment by jayesh9747** [comment]
> Hi @Nitish0777 @Madhu-mac @testgithubtiwari @EuclidStellar @thesuryac @memyselfandglitch @CodesSunny @lodha1503 @AkanshuAich @akashsingh011 @yashpatel139 @Harsh06-afk @Sumsum1231 @jayesh9747,
> 
> The contribution process will begin in a few weeks. However, if any of you are eager to start contributing, please feel free to let me know. I've scheduled a call for this Friday at 6 pm. Let's talk if you have any questions or doubts. C4GT discussion Friday, April 19 · 6:00 – 6:30pm Video call link: https://meet.google.com/vzo-oudm-yne

Is the meeting starting now?

**Comment by Madhu-mac** [comment]
> > Hi @Nitish0777 @Madhu-mac @testgithubtiwari @EuclidStellar @thesuryac @memyselfandglitch @CodesSunny @lodha1503 @AkanshuAich @akashsingh011 @yashpatel139 @Harsh06-afk @Sumsum1231 @jayesh9747,
> > The contribution process will begin in a few weeks. However, if any of you are eager to start contributing, please feel free to let me know. I've scheduled a call for this Friday at 6 pm. Let's talk if you have any questions or doubts. C4GT discussion Friday, April 19 · 6:00 – 6:30pm Video call link: https://meet.google.com/vzo-oudm-yne
> 
> Is the meeting starting now?

I'll be scheduled next week..

**Comment by RSN601KRI** [comment]
Hello, @aks30 @ankitpws , I would like to contribute to this project. I have the required skillset for it. Can you assign this project to me?

**Comment by Sufia-ahmad** [comment]
As a fresher, I want to do this project according to my skills set.

**Comment by hardik-pratap-singh** [comment]
Hey @ankitpws ! 
I am interested in this project. Can you please tell me about `Sunbird Knowlg Building Block` and where can I find its APIs ?

**Comment by AbhimanyuSamagra** [comment]
Do not ask process related questions about how to apply and who to contact in the above ticket. The only questions allowed are about technical aspects of the project itself. If you want help with the process, you can refer instructions listed on [Unstop](https://unstop.com/competitions/dedicated-mentoring-program-dmp-2024-code-for-govtech-932803?lb=7gWXVfKv) and any further queries can be taken up on our [Discord channel](https://discord.com/invite/VPrXf7Jxpr) titled DMP queries. Here's a [Video Tutorial](https://youtu.be/nMW-nD8WzHY) on how to submit a proposal for a project.

**Comment by Riyasharma28** [comment]
Good evening Respected Mentor @ankitpws 
I'm a Full Stack Developer proficient in HTML, CSS, JavaScript, MongoDB, React.js, Node.js, Bootstrap, Database Management, UI/UX Design. With over 10 projects completed in similar domains, I'm eager to contribute my expertise to the project. I'm excited about the opportunity to collaborate and drive its success. Looking forward to discussing further.

**Comment by parthgupta21** [comment]
Hi @aks30,

I am a MERN stack developer with a specialty in Backend Code. I have been working with NodeJs for around a year. I would like to contribute to this project.

**Comment by jayesh9747** [comment]
@aks30  meeting is going on or not ?

**Comment by reenakp2601** [comment]
Hello, @ankitpws  and @aks30 
I'm a Backend Developer proficient in Node.js, Express.js MongoDB, React.js, MySQL, PostgresSql, Bootstrap, Database Management, API building. I want to work on issues regarding API building. The project you mentioned, "ShikshaLokam," sounds intriguing, and I believe my skills align well with its goals. I'd love to learn more about it and discuss how I can be a part of the community. Looking forward to connecting further!

**Comment by vivekmishra9631** [comment]
Hi @dennyabrain , I'm Vivek Mishra, a third-year NIT Karnataka student with a strong passion for building impactful web applications. I'm excited to express my interest in the ml-survey-service project!

My background includes:

Full-Stack Development Experience: I honed my skills as a full-stack developer intern at aiRender for 6 months, working with JavaScript, ReactJS, Redux, and WebRTC. This experience solidified my understanding of both front-end and back-end development.

MERN Stack Expertise: In addition to my internship, I'm also a proficient MERN stack developer, comfortable working with MongoDB, Express, React, and Node.js. I also have good grip in SQL. This versatility allows me to tackle projects with both front-end and back-end components.

My problem-solving skills are further bolstered by my achievement of a gold medal at Worldquants Brain, demonstrating my ability to think critically and find efficient solutions.

I believe my technical skills, combined with my enthusiasm for building meaningful projects, make me a strong candidate to contribute to the project. I'm eager to learn more about the specific requirements and how my expertise can be utilized.

**Comment by reenakp2601** [comment]
Hello, @aks30 & @ankitpws 
I'm a Backend Developer proficient in Node.js, Express.js MongoDB, React.js, MySQL, PostgreSQL, Bootstrap, Database Management, API building & having a little experience with python and Django. I want to work on issues regarding API building and management as I am very much familiar with this. The project you mentioned, "ShikshaLokam," sounds intriguing, and I believe my skills align well with its goals. I'd love to learn more about it and discuss how I can be a part of the community. Looking forward to connecting further!

To understand this project and its code more deeply I want to set up this on my system but, in Readme.md the set-up guide includes-
Setting the keycloak
Create a folder on service directory named: keycloak-public-keys
Inside that folder create a file GRxxx....................xxxxx60fA
for keycloak file please contact Backend Team
Will you please guide me on this.

**Comment by supriyajathar** [comment]
Hello, @aks30 and @ankitpws! I'm excited to join the project and contribute my skills as a MERN stack developer, specializing in backend development. As a fresher, I'm eager to align my abilities with the project's needs.

**Comment by jayesh9747** [comment]
> Hello, @aks30 & @ankitpws I'm a Backend Developer proficient in Node.js, Express.js MongoDB, React.js, MySQL, PostgreSQL, Bootstrap, Database Management, API building & having a little experience with python and Django. I want to work on issues regarding API building and management as I am very much familiar with this. The project you mentioned, "ShikshaLokam," sounds intriguing, and I believe my skills align well with its goals. I'd love to learn more about it and discuss how I can be a part of the community. Looking forward to connecting further!
> 
> To understand this project and its code more deeply I want to set up this on my system but, in Readme.md the set-up guide includes- Setting the keycloak Create a folder on service directory named: keycloak-public-keys Inside that folder create a file GRxxx....................xxxxx60fA for keycloak file please contact Backend Team Will you please guide me on this.

Whoever is selected for the DMP will be provided with these files.

**Comment by reenakp2601** [comment]
> > Hello, @aks30 & @ankitpws I'm a Backend Developer proficient in Node.js, Express.js MongoDB, React.js, MySQL, PostgreSQL, Bootstrap, Database Management, API building & having a little experience with python and Django. I want to work on issues regarding API building and management as I am very much familiar with this. The project you mentioned, "ShikshaLokam," sounds intriguing, and I believe my skills align well with its goals. I'd love to learn more about it and discuss how I can be a part of the community. Looking forward to connecting further!
> > To understand this project and its code more deeply I want to set up this on my system but, in Readme.md the set-up guide includes- Setting the keycloak Create a folder on service directory named: keycloak-public-keys Inside that folder create a file GRxxx....................xxxxx60fA for keycloak file please contact Backend Team Will you please guide me on this.
> 
> Whoever is selected for the DMP will be provided with these files.

Then if I want to setup the project on my pc to explore more, what should I do. Or if scoring in github classroom assignment will work

**Comment by ivedmohan** [comment]
@ankitpws Heyy I would love to talk about the project as i have been also contributed to frontend utils library of shikshalokam and it would be really great if you could review my proposal

**Comment by reenakp2601** [comment]
> > Hello, @aks30 & @ankitpws I'm a Backend Developer proficient in Node.js, Express.js MongoDB, React.js, MySQL, PostgreSQL, Bootstrap, Database Management, API building & having a little experience with python and Django. I want to work on issues regarding API building and management as I am very much familiar with this. The project you mentioned, "ShikshaLokam," sounds intriguing, and I believe my skills align well with its goals. I'd love to learn more about it and discuss how I can be a part of the community. Looking forward to connecting further!
> > To understand this project and its code more deeply I want to set up this on my system but, in Readme.md the set-up guide includes- Setting the keycloak Create a folder on service directory named: keycloak-public-keys Inside that folder create a file GRxxx....................xxxxx60fA for keycloak file please contact Backend Team Will you please guide me on this.
> 
> Whoever is selected for the DMP will be provided with these files.

Did you attended that google meet, I have some more queries regarding this project.

**Comment by priyanka-TL** [comment]
# Weekly Goals 
## Week 1

- [x] Onboarding

## Week 2

- [x] Onboarding

## Week 3

- [x] Setup ML Survey service

## Week 4

- [x] Understand the code structure and flow


## Week 5

- [x] Understand the question response structure of current APIs

 ## Week 6

- [x] Understand the APIs of Sunbird Knowlg
- [x] Test the admin credentials and Creation apis

## Week 7
- [x] Complete the script for migrating the data

## Week 8
- [ ] Work on consumption side apis

**Comment by jayesh9747** [comment]
# Weekly  Learning 

## Week 1 
-  onboarding 

## Week 2 
- onboarding 

## Week 3 
- code review of  the ml - survey service 
- understand the schema  structure  of the question, question-set, solution, criteria and question-type 
- understand the  inquiry building block  codebase 

## Week 4 
- understand the APIs of  inquiry building regarding the migration script 
- learn lodash library for the optimization

## Week 5 
- write the migration script and optimize the code 

## Week 6 
- Get knowledge of csv -parse and csv-json  library.

## Week 7 
- How to make a mock server?
